server:
  port: 8080
spring:
  application:
    name: intelligent-chat
  mvc:
    static-path-pattern: /**
  datasource:
    url: jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.database}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${mysql.username}
    password: ${mysql.password}
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
      password: ${redis.password}
  servlet:
    multipart:
      # 单个文件最大大小
      max-file-size: 50MB
      # 所有上传文件最大大小
      max-request-size: 50MB

mybatis-plus:
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 控制台打印SQL（可选）
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
  type-aliases-package: cn.edu.zust.se.domain  # 实体类所在包
  mapper-locations: classpath*:mapper/**/*.xml  # 如果有 XML 文件

pgvector:
  database: ${postgres.database}
  host: ${postgres.host}
  port: ${postgres.port}
  user: ${postgres.user}
  password: ${postgres.password}
  table: ${postgres.table}

web:
  search:
    apikey: ${search.apikey}

search:
  apikey: ......
  engine: baidu

logging:
  level:
    root: info
  pattern:
    dateformat: HH:mm:ss:SSS

minio:
  endpoint: ${minio.endpoint} #Minio服务所在地址
  bucketName: ${minio.bucketName} #存储桶名称
  accessKey: ${minio.accessKey} #访问的key
  secretKey: ${minio.secretKey} #访问的秘钥

jwt:
  secret: ${jwt.secret}  # 必须是 Base64 编码的密钥（至少 256 位）
  expiration: 86400000  # Token 过期时间（单位：毫秒，默认 24 小时）

auth:
  excludePaths:
    - /user/login
    - /user/register